# Generated by Django 3.0.4 on 2020-04-04 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='Last_name',
            new_name='last_name',
        ),
    ]
