# Generated by Django 3.0.4 on 2020-04-04 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('Dev', 'Development'), ('UI', 'User Interface'), ('Dsg', 'Design'), ('Oth', 'Others')], max_length=20)),
                ('description', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('C', 'Just Created'), ('A', 'Under Analysis'), ('F', 'Found Root'), ('T', 'Terminated')], max_length=20)),
                ('count', models.IntegerField(default=0)),
                ('assignees', models.ManyToManyField(related_name='PS_assignee', to='accounts.UserDetail')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PS_createdby', to='accounts.UserDetail')),
            ],
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.CharField(max_length=100, null=True)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rootOfPS', to='PS.ProblemStatement')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100, null=True)),
                ('a_number', models.IntegerField(default=0)),
                ('givenBy', models.ManyToManyField(related_name='PS_givenby', to='accounts.UserDetail')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PS', to='PS.ProblemStatement')),
            ],
        ),
    ]
