# Generated by Django 3.0.4 on 2020-04-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='problemstatement',
            name='tags',
            field=models.ManyToManyField(related_name='tag', to='PS.Tag'),
        ),
    ]
