# Generated by Django 3.0.4 on 2020-04-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PS', '0002_auto_20200408_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='number',
            field=models.CharField(choices=[('bg-4f80b0', 'blue'), ('bg-424ee8', 'purple'), ('bg-36b7d7', 'sky blue'), ('bg-ef429e', 'dark grey'), ('bg-7cc576', 'green'), ('bg-6f7e9c', 'grey'), ('bg-f26522', 'orange'), ('bg-a3d39c', 'light green'), ('bg-92278f', 'pink')], max_length=25, null=True),
        ),
    ]
