# Generated by Django 3.0.4 on 2020-04-10 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PS', '0003_auto_20200409_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('color', models.CharField(choices=[('bg-4f80b0', 'blue'), ('bg-424ee8', 'purple'), ('bg-36b7d7', 'sky blue'), ('bg-ef429e', 'dark grey'), ('bg-7cc576', 'green'), ('bg-6f7e9c', 'grey'), ('bg-f26522', 'orange'), ('bg-a3d39c', 'light green'), ('bg-92278f', 'pink')], max_length=25, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='number',
            new_name='color',
        ),
        migrations.AlterField(
            model_name='problemstatement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='PS.Category'),
        ),
    ]
