# Generated by Django 3.0.5 on 2020-04-14 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PS', '0006_auto_20200412_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='a_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_parent', to='PS.Answer'),
        ),
    ]
